apiVersion: v1
kind: Service
metadata:
  name: mysql-np
  namespace: demo
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30007
  type: NodePort